### ISSUE TITLE
Infinitely repeated calls to MultiAPI when creating a MultiAPI-based application using pyinstaller

### ISSUE THREAD

**Issue by Hellogz** [NordicSemiconductor/pynrfjprog#14]
Works fine when pyinstaller is not in use，code:

def main():
    api = MultiAPI.MultiAPI('NRF52')
    print("get api done.")
    os.system("pause")

if __name__ == '__main__':
    main()

But an exception occurs after packaging with pyinstaller，command:
pyinstaller file_name.py

![Runtime screenshot](http://ww1.sinaimg.cn/large/6c1ebe8ely1g2kra4ujuqj207x077aa1.jpg)

if use API.API('NRF52') is normal.

How can I solve this problem?

**Comment by Hellogz** [comment]
python 3.6.4, pyinstaller 3.4 windows XP 32bit and windows 10 64bit

**Comment by simtind** [comment]
This looks like an issue in pyinstaller. See their documentation for a workaround:
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing
