### ISSUE TITLE
Provide artifacts of the nrfjprog library for arm architecture

### ISSUE THREAD

**Issue by douzepouze** [NordicSemiconductor/pynrfjprog#21]
Thank you for the great tool. 
It would be super helpful if the nrfjprog.so would be available for ARM, so the package could be used on a e.g. raspberry pi. 
SEGGER already provides the necessary libjlinkarm.so build for 32-bit ARM.

**Comment by simtind** [comment]
Linux-ARM libraries are now available 10.14.0 🎉

**Comment by efra-mx** [comment]
> Linux-ARM libraries are now available 10.14.0 :tada: 

There is an issue with this version:
https://github.com/NordicSemiconductor/pynrfjprog/issues/24

Use  10.15.2 or newer
